### ISSUE TITLE
Unable to read PCI information: pci config file has an invalid format

### ISSUE THREAD

**Issue by mszaro** [hertg/egpu-switcher#122]
Hey there, I'm running into an issue that seems related to https://github.com/hertg/egpu-switcher/issues/91: 

```
mszaro@miniserv:~$ sudo egpu-switcher config
[error] unable to read pci information from sysfs: got error while scanning device '0000:04:01.0': the pci 'config' file has an invalid format
```

This is with 0.19.0, manually installed by pulling the binary.

The device in question as seen by `lspci`: 

```
04:01.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge DD 2018] (rev 06) (prog-if 00 [Normal decode])
        Subsystem: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge DD 2018]
        !!! Unknown header type 7f
        Interrupt: pin ? routed to IRQ 127
        IOMMU group: 18
        I/O behind bridge: 00006000-00006fff [size=4K] [32-bit]
        Memory behind bridge: 5e000000-5e2fffff [size=3M] [32-bit]
        Prefetchable memory behind bridge: 0000006000000000-000000640fffffff [size=16640M] [64-bit]
        Kernel driver in use: pcieport
```

This seems to be unrelated to my actual eGPU setup, but for the sake of completeness, it's an RX 7800M in an external enclosure. I haven't installed any drivers manually, just attempting to roll with the `amdgpu` support already in the kernel. (Linux Mint 22 x64, kernel 6.8.0-49-generic).

**Comment by hertg** [comment]
Might be an issue similar to #119, which I wasn't able to reproduce/resolve at the time. If you could provide me the original `config` file for your device at `04:01.0`, maybe it would be possible to debug this one. (see my [comment here](https://github.com/hertg/egpu-switcher/issues/119#issuecomment-2180342321) for instructions on how you can send it to me in encrypted form).

The `!!! Unknown header type 7f` in your lspci output makes me think that maybe my gopci library can't handle that device, maybe it reports an unexptect/invalid configuration...

**Comment by mszaro** [comment]
Well, that's interesting. I would be happy to send it to you, but I think I just worked out why it doesn't parse; it's empty!

```
mszaro@miniserv:/sys/bus/pci/devices/0000:04:01.0$ du config
0       config
```

**Comment by hertg** [comment]
Thanks for looking it up, yeah that's weird. And I agree, it should probably handle this error gracefully. I may need to address that in my [gopci](https://github.com/hertg/gopci) library. I really wonder where that invalid config file is coming from, though.

**Comment by mszaro** [comment]
Yeah, I have no idea. I'm no expert on the spec by any means, but at least as a layman Linux user I wouldn't expect /pci/.../config to be absent. It isn't, on any other devices on the system.

**Comment by a9e78rauijasdf** [comment]
Im having the same issue - TB4 <-> eGPU - Ubuntu 24.04.3 LTS:

`# egpu-switcher config
[error] unable to read pci information from sysfs: got error while scanning device '0000:51:00.0': the pci 'config' file has an invalid format
panic: unable to read pci information from sysfs

goroutine 1 [running]:
github.com/hertg/egpu-switcher/internal/pci.ReadGPUs()
        /home/runner/work/egpu-switcher/egpu-switcher/internal/pci/pci.go:98 +0x1a5
github.com/hertg/egpu-switcher/cmd.init.func2(0xc000507700?, {0x816cc0?, 0x4?, 0x816cc4?})
        /home/runner/work/egpu-switcher/egpu-switcher/cmd/config.go:26 +0x2f
github.com/spf13/cobra.(*Command).execute(0xb6c920, {0xb98920, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xb6c360)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/hertg/egpu-switcher/cmd.Execute()
        /home/runner/work/egpu-switcher/egpu-switcher/cmd/root.go:79 +0x1a
main.main()
        /home/runner/work/egpu-switcher/egpu-switcher/main.go:8 +0xf
`

`# ls -l /sys/bus/pci/devices/0000\:51\:00.0/config 
-rw-r--r-- 1 root root 4096 Nov 18 22:00 /sys/bus/pci/devices/0000:51:00.0/config
# file /sys/bus/pci/devices/0000\:51\:00.0/config
/sys/bus/pci/devices/0000:51:00.0/config: ISO-8859 text, with very long lines (4096), with no line terminators
`

Im on the Nvidia proprietary 580 driver.
